network:
  version: 2
  renderer: networkd
  ethernets:
    ens3: # Substitua 'ens3' pelo nome da interface de rede do seu servidor.
      dhcp4: no
      addresses:
        - 192.168.0.100/24 # IP estático da rede interna (LAN)
      gateway4: 192.168.0.1 # IP do roteador (gateway)
      nameservers:
        addresses:
          - 8.8.8.8
          - 8.8.4.4
